application:
  name: "otel-sp-test"
  
mulesoft-bridge-db-aws:
  host: "cab-test-mulesoftbridge-db.c51x0u8xgvqi.eu-west-2.rds.amazonaws.com"
  db: "MuleSoftBridge"               
    
ad-logger:
 log-level:
   service: "DEBUG"
   adapter: "DEBUG"
   debug: "DEBUG"
   error: "DEBUG"
 pretty-print: "false" 