api:
  http:
    listener:
      ssl:
        keyPassword: "![LYeCxr08Yos8zDpbtYvrD7umyrZTy5rAdXrB7uZQeJc=]"
        password: "![LYeCxr08Yos8zDpbtYvrD7umyrZTy5rAdXrB7uZQeJc=]"
  
mulesoft-bridge-db-aws:
  user: "![nFFHU1oIFQNCxXj5g+WiUQ==]"
  password: "![o3Fa6bbCFoQ6cWmOqkQpbw==]"      